# Generated by Django 2.0 on 2020-06-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True, verbose_name='ID пользователя')),
                ('full_name', models.CharField(help_text='ФИО', max_length=500, verbose_name='ФИО')),
                ('is_active', models.BooleanField(default=False)),
                ('date_create', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
